# CI and PR triggers
trigger:
- main
- rel/*

pr:
- main
- rel/*

variables:
# Cannot use key:value syntax in root defined variables
- name: _TeamName
  value: UnitTesting
- name: CodeQL.Enabled
  value: false
- name: _RunAsInternal
  value: True
- name: _RunAsPublic
  value: False
# _SignType and _Sign are required for signing even if not used directly here
- name: _SignType
  value: real
- name: _Sign
  value: True

# Group gives access to $microsoft-symbol-server-pat and $symweb-symbol-server-pat
- group: DotNet-Symbol-Server-Pats
# Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
- group: Publish-Build-Assets
# Group gives access to $dn-bot-devdiv-drop-rw-code-rw and dn-bot-dnceng-build-rw-code-rw
- group: DotNet-VSTS-Infra-Access
- group: DotNet-DevDiv-Insertion-Workflow-Variables
- name: VisualStudioDropName
  value: Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)
- name: _BuildConfig
  value: Release

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      policheck:
        enabled: true
    featureFlags:
      autoBaseline: true
    pool:
      name: netcore1espool-internal
      image: windows.vs2022preview.amd64
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: build
      displayName: Build
      jobs:

      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enableMicrobuild: true
          enablePublishBuildArtifacts: true
          enablePublishBuildAssets: true
          enablePublishUsingPipelines: true
          enablePublishTestResults: true
          enableTelemetry: true
          enableSourceBuild: true
          testResultsFormat: 'vstest'
          helixRepo: dotnet/test-templates
          jobs:
          - job: Windows
            pool:
              name: netcore1espool-internal
              image: windows.vs2022preview.amd64
              os: windows

            steps:
            - checkout: self
              clean: true

            - task: NuGetAuthenticate@1
              inputs:
                nuGetServiceConnections: 'devdiv/dotnet-core-internal-tooling'
                forceReinstallCredentialProvider: true

            - script: eng\common\cibuild.cmd
                -configuration $(_BuildConfig)
                -prepareMachine
                /p:TeamName=$(_TeamName)
                /p:VisualStudioDropName=$(VisualStudioDropName)
                /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                /p:DotNetPublishUsingPipelines=true
                /p:DotNetArtifactsCategory=.NETCore
                /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
                /p:GenerateSbom=true
              displayName: Build

            - task: 1ES.PublishBuildArtifacts@1
              displayName: 'Publish VSSetup'
              inputs:
                PathtoPublish: '$(Build.SourcesDirectory)/artifacts/VSSetup/$(_BuildConfig)'
                ArtifactName: VSSetupArtifacts

            - task: DotNetCoreCLI@2
              displayName: 'Acceptance tests'
              inputs:
                command: test
                projects: 'test\Microsoft.TestTemplates.Acceptance.Tests.sln'
                publishTestResults: false
                arguments: '--configuration $(_BuildConfig) --logger trx --results-directory $(Build.SourcesDirectory)/artifacts/TestResults/$(_BuildConfig)'

            - task: 1ES.PublishBuildArtifacts@1
              displayName: 'Publish acceptance tests logs'
              inputs:
                PathtoPublish: '$(Build.SourcesDirectory)/artifacts/bin/Microsoft.TestTemplates.Acceptance.Tests/Debug/net9.0/TestResults/Microsoft.TestTemplates.Acceptance.Tests_net9.0_x64.log'
                ArtifactName: AcceptanceTestsLogs
              condition: failed()

            - script: dir /S artifacts\VSSetup\$(_BuildConfig)\Insertion
              displayName: 'List Insertion files to upload'

            - task: 1ES.MicroBuildVstsDrop@1
              displayName: Upload Azure DevOps Drop
              inputs:
                dropName: $(VisualStudioDropName)
                dropFolder: 'artifacts\VSSetup\$(_BuildConfig)\Insertion'
                accessToken: $(dn-bot-devdiv-drop-rw-code-rw)
              condition: succeeded()

      - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
        - template: /eng/common/templates-official/job/onelocbuild.yml@self
          parameters:
            GitHubOrg: dotnet
            MirrorRepo: test-templates
            LclSource: lclFilesfromPackage
            LclPackageId: 'LCL-JUNO-PROD-TESTEMPLATE'

    - template: \eng\common\templates-official\post-build\post-build.yml@self
      parameters:
        enableSourceLinkValidation: false
        publishingInfraVersion: 3
